workspace = { members = ["solid", "macros", "coupling_and_cohesion"] }
[package]
name = "better-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
